---
kind: abc

steps:
- name: build
  image: node:8
  secrets: [ test ]
  commands:
  # - yarn install
  - yarn test
  - echo $TEST
  # - sleep 30

- name: prod
  image: node:8
  commands:
  - echo "prod"
  when:
    event: [ promote ]
    target: [ prod ]

- name: test
  image: node:8
  commands:
  - echo "uat"
  when:
    event: [ promote ]
    target: [ uat ]

# ---
# pipeline:
#   frontend:
#     image: node:8
#     secrets: [ test ]
#     commands:
#       - echo "frontend"
#       - echo $TEST
#   backend:
#     image: node:8
#     commands:
#       - echo "backend"
#       - echo $TEST
#   deploy:
#     image: node:8
#     commands:
#       - echo "deploy"
#     when:
#       local: false
# ...      
# kind: pipeline
# type: docker
# name: default

# # steps:
# # - name: build
# #   image: node:8
# #   commands:
# #   - yarn install
# #   - yarn run build
# steps:
#   - name: build
#     image: node:8
#     secrets: [ TEST_MATT ]
#     commands:
#     - npm run test
#     - echo $test
#     - echo $TEST_MATT
#   - name: deploy
#     image: node:8
#     commands:
#       - echo "deploy"
#     when:
#       local: false